"""Faceless Champ: programmatic animated videos for developers and agents."""

from .animation import (
    Animation,
    BounceIn,
    Draw,
    FadeIn,
    FadeOut,
    PopIn,
    PopOut,
    Pulse,
    Shake,
    SlideIn,
    SlideOut,
    SpinIn,
    Typewriter,
    Wiggle,
    Write,
    ZoomIn,
    ZoomOut,
    ease_in,
    ease_out,
    linear,
    smooth,
)
from .cli import main as main
from .colors import COLOR_SCHEMES, ColorScheme, with_alpha
from .components import (
    Arrow,
    Canvas,
    Circle,
    Component,
    Equation,
    Icon,
    Image,
    Line,
    Polyline,
    Rectangle,
    Square,
    Text,
    Triangle,
)
from .export import ExportSettings, render
from .renderer import PillowRenderer, Renderer
from .subtitles import Captions, SubtitleCue, SubtitleTrack
from .timeline import Grid, Layer, Scene, Sequence

__all__ = [
    "COLOR_SCHEMES",
    "Animation",
    "Arrow",
    "BounceIn",
    "Canvas",
    "Captions",
    "Circle",
    "ColorScheme",
    "Component",
    "Draw",
    "Equation",
    "ExportSettings",
    "FadeIn",
    "FadeOut",
    "Grid",
    "Icon",
    "Image",
    "Layer",
    "Line",
    "PillowRenderer",
    "Polyline",
    "PopIn",
    "PopOut",
    "Pulse",
    "Rectangle",
    "Renderer",
    "Scene",
    "Sequence",
    "Shake",
    "SlideIn",
    "SlideOut",
    "SpinIn",
    "Square",
    "SubtitleCue",
    "SubtitleTrack",
    "Text",
    "Triangle",
    "Typewriter",
    "Wiggle",
    "Write",
    "ZoomIn",
    "ZoomOut",
    "ease_in",
    "ease_out",
    "linear",
    "render",
    "smooth",
    "with_alpha",
]
__version__ = "0.1.0"
