"""Faceless Champ: programmatic animated videos for developers and agents."""

from .animation import (
    Animation,
    BounceIn,
    ChartReveal,
    Draw,
    FadeIn,
    FadeOut,
    PopIn,
    PopOut,
    Pulse,
    Shake,
    SlideIn,
    SlideOut,
    SpinIn,
    Typewriter,
    Wiggle,
    Write,
    ZoomIn,
    ZoomOut,
    ease_in,
    ease_out,
    linear,
    smooth,
)
from .charts import (
    Axis,
    BarChart,
    Chart,
    ChartStyle,
    Heatmap,
    Histogram,
    LineChart,
    NetworkGraph,
    PieChart,
    RankedBarChart,
    SankeyChart,
    ScatterPlot,
    VectorField,
)
from .cli import main as main
from .colors import COLOR_SCHEMES, ColorScheme, with_alpha
from .components import (
    Arrow,
    Canvas,
    Circle,
    Component,
    Ellipse,
    Equation,
    Icon,
    Image,
    ImageSlot,
    Line,
    Number,
    Polyline,
    Rectangle,
    Square,
    Text,
    Triangle,
)
from .export import ExportSettings, render
from .flags import Flag, flag_path, supported_flags
from .maps import EarthMap, OutlineMap, SatelliteMap, supported_countries
from .renderer import PillowRenderer, Renderer
from .subtitles import Captions, SubtitleCue, SubtitleTrack
from .timeline import Grid, Layer, Scene, Sequence

__all__ = [
    "COLOR_SCHEMES",
    "Animation",
    "Arrow",
    "Axis",
    "BarChart",
    "BounceIn",
    "Canvas",
    "Captions",
    "Chart",
    "ChartReveal",
    "ChartStyle",
    "Circle",
    "ColorScheme",
    "Component",
    "Draw",
    "EarthMap",
    "Ellipse",
    "Equation",
    "ExportSettings",
    "FadeIn",
    "FadeOut",
    "Flag",
    "Grid",
    "Heatmap",
    "Histogram",
    "Icon",
    "Image",
    "ImageSlot",
    "Layer",
    "Line",
    "LineChart",
    "NetworkGraph",
    "Number",
    "OutlineMap",
    "PieChart",
    "PillowRenderer",
    "Polyline",
    "PopIn",
    "PopOut",
    "Pulse",
    "RankedBarChart",
    "Rectangle",
    "Renderer",
    "SankeyChart",
    "SatelliteMap",
    "ScatterPlot",
    "Scene",
    "Sequence",
    "Shake",
    "SlideIn",
    "SlideOut",
    "SpinIn",
    "Square",
    "SubtitleCue",
    "SubtitleTrack",
    "Text",
    "Triangle",
    "Typewriter",
    "VectorField",
    "Wiggle",
    "Write",
    "ZoomIn",
    "ZoomOut",
    "ease_in",
    "ease_out",
    "flag_path",
    "linear",
    "render",
    "smooth",
    "supported_countries",
    "supported_flags",
    "with_alpha",
]
__version__ = "0.1.0"
