"""Faceless Champ: programmatic animated videos for developers and agents."""

from .animation import (
    Animation,
    BounceIn,
    Draw,
    FadeIn,
    FadeOut,
    PopIn,
    PopOut,
    Pulse,
    Shake,
    SlideIn,
    SlideOut,
    SpinIn,
    Typewriter,
    Wiggle,
    ZoomIn,
    ZoomOut,
    ease_in,
    ease_out,
    linear,
    smooth,
)
from .cli import main as main
from .components import Arrow, Canvas, Circle, Component, Icon, Image, Line, Rectangle, Square, Text, Triangle
from .export import ExportSettings, render
from .renderer import PillowRenderer, Renderer
from .subtitles import Captions, SubtitleCue, SubtitleTrack
from .timeline import Grid, Scene, Sequence

__all__ = [
    "Animation",
    "Arrow",
    "BounceIn",
    "Canvas",
    "Captions",
    "Circle",
    "Component",
    "Draw",
    "ExportSettings",
    "FadeIn",
    "FadeOut",
    "Grid",
    "Icon",
    "Image",
    "Line",
    "PillowRenderer",
    "PopIn",
    "PopOut",
    "Pulse",
    "Rectangle",
    "Renderer",
    "Scene",
    "Sequence",
    "Shake",
    "SlideIn",
    "SlideOut",
    "SpinIn",
    "Square",
    "SubtitleCue",
    "SubtitleTrack",
    "Text",
    "Triangle",
    "Typewriter",
    "Wiggle",
    "ZoomIn",
    "ZoomOut",
    "ease_in",
    "ease_out",
    "linear",
    "render",
    "smooth",
]
__version__ = "0.1.0"
